name: Report a Bug
description: Report something that isn't working correctly
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Report a Bug
        Use this form to report something that isn't working as expected.
        
  - type: textarea
    id: what-happened
    attributes:
      label: What's Not Working?
      description: Describe the problem you're experiencing
      placeholder: "e.g., Students can't sign up for activities, login button doesn't work, activities don't show up"
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Tell us how to see the problem happen
      placeholder: |
        1. Go to the website
        2. Click on '...'
        3. Enter '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: What Should Happen Instead?
      description: Describe what you expected to happen
      placeholder: "e.g., The student should be added to the activity, the login should work"
    validations:
      required: true
      
  - type: dropdown
    id: frequency
    attributes:
      label: How Often Does This Happen?
      description: Is this a consistent problem or does it happen occasionally?
      options:
        - Every time
        - Sometimes
        - Once or twice
        - Not sure
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: How Serious Is This Problem?
      description: How much does this affect using the website?
      options:
        - Critical - The website is unusable
        - High - Major feature doesn't work
        - Medium - Minor feature doesn't work
        - Low - Small inconvenience
    validations:
      required: true
      
  - type: textarea
    id: error-message
    attributes:
      label: Error Messages
      description: If you see any error messages, copy them here
      placeholder: "Paste any error messages or unusual text you see"
    validations:
      required: false
      
  - type: dropdown
    id: browser
    attributes:
      label: What Browser Are You Using?
      description: Which web browser are you using when this happens?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
        - Not sure
    validations:
      required: false
      
  - type: dropdown
    id: device
    attributes:
      label: What Device Are You Using?
      description: What type of device are you using?
      options:
        - Desktop/Laptop Computer
        - Tablet
        - Smartphone
        - Not sure
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Anything else that might help us understand the problem
      placeholder: "Optional: Screenshots, when it started happening, etc."
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        ---
        ## Acceptance Criteria
        - The reported bug is identified and understood
        - A fix is implemented that resolves the issue
        - The fix is tested to ensure it works correctly
        - The problem no longer occurs when following the reproduction steps
