blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Psarmmiey/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Learn how to set up and develop the application
  - name: 💬 General Question
    url: https://github.com/Psarmmiey/skills-expand-your-team-with-copilot/discussions
    about: Ask questions and discuss with the community
