name: Modify Existing Activity
description: Request changes to an existing extracurricular activity
title: "[Modify Activity]: "
labels: ["enhancement", "activity"]
body:
  - type: markdown
    attributes:
      value: |
        ## Modify an Existing Activity
        Use this form to request changes to an activity that already exists in the system.
        
  - type: input
    id: activity-name
    attributes:
      label: Activity Name
      description: Which activity needs to be modified?
      placeholder: "e.g., Chess Club, Soccer Team, Art Club"
    validations:
      required: true
      
  - type: checkboxes
    id: what-to-change
    attributes:
      label: What needs to be changed?
      description: Select all items that need to be modified
      options:
        - label: Activity name
        - label: Description
        - label: Schedule (days and/or times)
        - label: Maximum number of participants
        - label: Other changes
    validations:
      required: true
      
  - type: input
    id: new-name
    attributes:
      label: New Activity Name (if changing name)
      description: What should the new name be?
      placeholder: "Leave blank if not changing the name"
    validations:
      required: false
      
  - type: textarea
    id: new-description
    attributes:
      label: New Description (if changing description)
      description: What should the new description be?
      placeholder: "Leave blank if not changing the description"
    validations:
      required: false
      
  - type: checkboxes
    id: new-days
    attributes:
      label: New Days (if changing schedule)
      description: Select the new days when this activity will meet
      options:
        - label: Monday
        - label: Tuesday
        - label: Wednesday
        - label: Thursday
        - label: Friday
        - label: Saturday
        - label: Sunday
    validations:
      required: false
      
  - type: input
    id: new-start-time
    attributes:
      label: New Start Time (if changing schedule)
      description: New start time in 24-hour format
      placeholder: "e.g., 15:30 for 3:30 PM"
    validations:
      required: false
      
  - type: input
    id: new-end-time
    attributes:
      label: New End Time (if changing schedule)
      description: New end time in 24-hour format
      placeholder: "e.g., 17:00 for 5:00 PM"
    validations:
      required: false
      
  - type: input
    id: new-max-participants
    attributes:
      label: New Maximum Participants (if changing limit)
      description: New maximum number of students
      placeholder: "e.g., 25"
    validations:
      required: false
      
  - type: textarea
    id: other-changes
    attributes:
      label: Other Changes
      description: Describe any other changes needed
      placeholder: "Explain what else needs to be changed and why"
    validations:
      required: false
      
  - type: textarea
    id: reason
    attributes:
      label: Reason for Change
      description: Why is this change needed?
      placeholder: "e.g., Need more time for the activity, room availability changed, increased student interest"
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        ---
        ## Acceptance Criteria
        - The activity is updated with all requested changes
        - The changes are visible in the activities list
        - Students can still sign up for the activity
        - Existing participants remain enrolled (unless specifically requested to remove them)
        - The activity appears correctly in all relevant filters
